name: vibe_music
description: A new Flutter project.
publish_to: 'none' 
version: 0.4.2+4

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  youtube_explode_dart: ^1.12.3
  provider: ^6.0.4
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  google_fonts: ^3.0.1
  palette_generator: ^0.3.3+2
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  miniplayer: ^1.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  dynamic_color: ^1.5.4
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.1.7
  expandable_page_view: ^1.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
