name: gyavun
description: Flutter application for streaming music from Jio Saavn
publish_to: 'none'
version: 0.9.4+13

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  audio_service: ^0.18.10
  audio_video_progress_bar: ^1.0.1
  dart_des: ^1.0.2
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^8.2.0
  google_fonts: any
  http: any
  iconsax: ^0.0.8
  just_audio: ^0.9.34
  provider: ^6.0.5
  sliding_up_panel: ^2.0.0+1
  logging: any
  duration_picker: ^1.1.1
  flutter_displaymode: ^0.6.0
  flutter_swipe_action_cell: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  dropdown_button2: ^2.1.4
  cached_network_image: ^3.2.3
  dynamic_color: ^1.6.5
  flutter_lyric: ^2.0.4+6
  flip_card: ^0.7.0
  permission_handler: ^10.4.1
  al_downloader: ^1.7.4
  metadata_god: ^0.5.0
  flutter_progress_status: ^0.0.3
  path_provider: ^2.0.15
  youtube_explode_dart: ^1.12.4
  palette_generator: ^0.3.3+2
  change_app_package_name: ^1.1.0
  just_audio_cache: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
